stead/event/models.py
class EventPost(db.Model):
    # Setup the relationship to the User table
    # Model for the Blog Posts on Website
    id = db.Column(db.Integer, primary_key=True)
    # Notice how we connect the BlogPost to a particular author
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    title = db.Column(db.String(140), nullable=False)
    text = db.Column(db.Text, nullable=False)
    date_of_event = db.Column(db.DateTime, nullable=False)
    picture = db.Column(db.String(20), nullable=False, default='default_profile.png')

    def __repr__(self):
        return '<BlogPost> %r' % self.title, self.text, self.picture, self.user_id

stead/projects/models.py
from stead import db
from datetime import datetime


class Project(db.Model):

    __tablename__ = 'projects'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    content = db.Column(db.TEXT, nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    youtube_id = db.Column(db.String(20))

stead/forum/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from flask_pagedown.fields import PageDownField


class PostForm(FlaskForm):
    content = TextAreaField("What's on your mind?", validators=[DataRequired()])
    submit = SubmitField('Post')


class CommentForm(FlaskForm):
    body = TextAreaField('What is your comment about my post?', validators=[DataRequired()])
    submit = SubmitField('Post')

stead/core/views.py
from flask import render_template, Blueprint, make_response, redirect, url_for
from stead.models import db, User, ClassRegistration
from stead.news_posts.models import NewsPost
from flask_login import login_required
from stead.users.forms import ClassRegistrationForm

core = Blueprint('core', __name__)


@core.route('/')
def home():
    members = len(User.query.all())
    male = User.query.filter_by(gender='male').count()
    female = User.query.filter_by(gender='female').count()
    news_post = NewsPost.query.order_by(NewsPost.date.desc()).all()
    return render_template('home.html', members=members, male=male, female=female, news_post=news_post)


@core.route('/account')
def account():
    return render_template('account.html', title='User Profile')


@core.route('/all')
@login_required
def show_all():
    resp = make_response(redirect(url_for('forum.chat')))
    resp.set_cookie('show_followed', '', max_age=30 * 24 * 60 * 60)  # 30 days
    return resp


@core.route('/followed')
@login_required
def show_followed():
    resp = make_response(redirect(url_for('forum.chat')))
    resp.set_cookie('show_followed', '1', max_age=30 * 24 * 60 * 60)  # 30 days
    return resp


@core.route('/about')
def about():
    return render_template('about.html', title='About Page')


@core.route('/events')
def events():
    return render_template('events.html', title='Events')


@core.route('/events/space-competition-sierra-leone')
def competition():
    return render_template('space_competition_sierra_leone.html',
                           title='SPACE SCIENCE AND ASTRONOMY COMPETITION IN SIERRA LEONE')


@core.route('/events/capacity_building', methods=['GET', 'POST'])
def capacity_building():
    form = ClassRegistrationForm()
    if form.validate_on_submit():
        user = ClassRegistration(first_name=form.firstName.data, middle_name=form.middleName.data,
                                 last_name=form.lastName.data,
                                 email=form.email.data,
                                 address=form.address.data,
                                 phone_no=form.phoneNumber.data, course1=form.course1.data,
                                 course2=form.course2.data, course3=form.course3.data, course4=form.course4.data, )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('core.home'))
    return render_template('capacity_building.html', title='Capacity Building', form=form)


@core.route('/events/student_list')
@login_required
def student_list():
    students = ClassRegistration.query.all()
    return render_template('student_list.html', title='Student List', students=students)

stead/forum/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from stead import db
from stead.forum.forms import PostForm, CommentForm
from stead.models import Post, User, Comment

forum = Blueprint('forum', __name__)


@forum.route('/forum')
def forums():
    general = Post.query.order_by(Post.date_posted.desc())[0]
    general_num = len(Post.query.all())

    return render_template('forum.html', title='Forum Blog', general=general, general_num=general_num)


@forum.route('/forum/general', methods=['GET', 'POST'])
@login_required
def chat():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(content=form.content.data, user_id=current_user.id)

        db.session.add(post)
        db.session.commit()
        return redirect(url_for('forum.chat'))
    page = request.args.get('page', 1, type=int)
    show_followed = False
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_posts
    else:
        query = Post.query
    pagination = query.order_by(Post.date_posted.desc()).paginate(
        page, per_page=10,
        error_out=False)
    posts = pagination
    return render_template('chat_page.html', posts=posts, form=form, title='Forum', show_followed=show_followed, pagination=pagination)


@forum.route('/forum/general/comment/<int:id>', methods=['GET', 'POST'])
@login_required
def post(id):
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data, post=post, author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been published.')
        return redirect(url_for('forum.post', id=post.id))
    pagination = post.comments.order_by(Comment.timestamp)

    return render_template('post.html', posts=[post], form=form, comments=pagination, title="Comment")


@forum.route('/forum/user/<username>')
@login_required
def user_posts(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc())
    return render_template('user_forum.html', user=user, posts=posts)


@forum.route("/forum/<int:blog_post_id>/delete")
@login_required
def delete_post(blog_post_id):
    post = Post.query.get_or_404(blog_post_id)
    comment = Comment.query.filter_by(post_id=None).all()
    for n in comment:
        b = Comment.query.get_or_404(n.id)
        db.session.delete(n)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('forum.chat'))

stead/projects/views.py
from flask import render_template, Blueprint

projects = Blueprint('projects', __name__)


@projects.route('/project')
def project():
    return render_template('project.html', title='Project Page')


@projects.route('/projects_link')
def projects_link():
    return render_template('projects_link.html', title='Project Page')

stead/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from stead import db, app
from stead.models import User, Permission, Follow, Role
from stead.users.forms import RegistrationForm, LoginForm, EditNameForm, EditPasswordForm, PasswordResetRequestForm, \
    PasswordResetForm, FinancialForm, ChangeProfileForm
from flask_uploads import UploadSet, configure_uploads, DOCUMENTS
from werkzeug.security import generate_password_hash
from stead.users.picture_handler import save_picture, residue_profile_pics
from stead.decorator import admin_required, permission_required
from stead.email import send_email

users = Blueprint('users', __name__)

doc = UploadSet('photos', DOCUMENTS)
app.config['UPLOADED_PHOTOS_DEST'] = 'stead/static/financial_doc'
upload = configure_uploads(app, doc)


@users.before_app_request
def before_request():
    if current_user.is_authenticated \
            and not current_user.confirmed \
            and request.blueprint != 'users' \
            and request.endpoint != 'static':
        return redirect(url_for('users.unconfirmed'))


@users.route('/unconfirmed')
def unconfirmed():
    if current_user.is_anonymous or current_user.confirmed:
        return redirect(url_for('users.login'))
    return render_template('auth/unconfirmed.html')


@users.route('/account/<username>')
def account(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('faccount.html', title='Account Page', user=user)


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        if form.picture.data:

            picture_file = save_picture(form.picture.data, 'profile_pics', (125, 125))
            # picture_file = photos.save(form.picture.data)
            user = User(first_name=form.firstName.data, middle_name=form.middleName.data, last_name=form.lastName.data,
                        username=form.username.data, email=form.email.data, birthday=form.dateOfBirth.data,
                        profile_image=picture_file, address=form.address.data,
                        phone_no=form.phoneNumber.data, gender=form.gender.data, password=form.password.data)

            db.session.add(user)
        else:
            user = User(first_name=form.firstName.data, middle_name=form.middleName.data, last_name=form.lastName.data,
                        username=form.username.data, email=form.email.data, birthday=form.dateOfBirth.data,
                        address=form.address.data,
                        phone_no=form.phoneNumber.data, gender=form.gender.data, password=form.password.data)

            db.session.add(user)
        db.session.commit()

        token = user.generate_confirmation_token()
        send_email(user.email, 'Confirm Your Account',
                   'auth/email/confirm', user=user, token=token)
        flash('A confirmation email has been sent to you by email.')

        return redirect(url_for('core.home'))
    return render_template('auth/registration.html', form=form)


@users.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('core.home'))
    if current_user.confirm(token):
        db.session.commit()
        flash('You have confirmed your account. Thanks!')
    else:
        flash('The confirmation link is invalid or has expired.')
    return redirect(url_for('core.home'))


@users.route('/confirm')
@login_required
def resend_confirmation():
    token = current_user.generate_confirmation_token()
    send_email(current_user.email, 'Confirm Your Account',
               'auth/email/confirm', user=current_user, token=token)
    flash('A new confirmation email has been sent to you by email.')
    return redirect(url_for('core.home'))


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()

        # Check that the user was supplied and the password is right
        # The verify_password method comes from the User object
        # https://stackoverflow.com/questions/2209755/python-operation-vs-is-not

        if user.check_password(form.password.data) and user is not None:
            # Log in the user

            login_user(user)
            flash('Logged in successfully.')

            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0] == '/':
                next = url_for('core.home')

            return redirect(next)
    return render_template('auth/login.html', form=form, title="Log In")


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.home'))


@users.route("/account/edit_name", methods=['GET', 'POST'])
@login_required
def edit_name():
    form = EditNameForm()

    if form.validate_on_submit():

        current_user.first_name = form.firstName.data
        current_user.last_name = form.lastName.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('core.account'))

    elif request.method == 'GET':
        form.firstName.data = current_user.first_name
        form.lastName.data = current_user.last_name

    return render_template('editUsername.html', form=form, title='Profile | Edit Name')


@users.route("/account/edit_password", methods=['GET', 'POST'])
@login_required
def edit_password():
    form = EditPasswordForm()

    if form.validate_on_submit():
        current_user.password_hash = generate_password_hash(form.new_password.data)

        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('core.account'))

    return render_template('changePassword.html', form=form, title='Profile | Edit Password')


@users.route('/follow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('core.home'))
    if current_user.is_following(user):
        flash('You are already following this user.')
        return redirect(url_for('users.account', username=username))
    current_user.follow(user)
    db.session.commit()
    flash('You are now following %s.' % username)
    return redirect(url_for('users.account', username=username))


@users.route('/followers/<username>')
def followers(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('core.home'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followers.paginate(
        page, per_page=10,
        error_out=False)
    follows = [{'user': item.follower, 'timestamp': item.timestamp}
               for item in pagination.items]
    return render_template('followers.html', user=user, title="Followers of",
                           endpoint='users.followers', pagination=pagination,
                           follows=follows)


@users.route('/unfollow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('.index'))
    if not current_user.is_following(user):
        flash('You are not following this user.')
        return redirect(url_for('users.account', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are not following %s anymore.' % username)
    return redirect(url_for('users.account', username=username))


@users.route('/followed_by/<username>')
def followed_by(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followed.paginate(
        page, per_page=20,
        error_out=False)
    follows = [{'user': item.followed, 'timestamp': item.timestamp}
               for item in pagination.items]
    return render_template('followers.html', user=user, title="Followed by",
                           endpoint='users.followed_by', pagination=pagination,
                           follows=follows)


@users.route('/reset', methods=['GET', 'POST'])
def password_reset_request():
    if not current_user.is_anonymous:
        return redirect(url_for('core.home'))
    form = PasswordResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:
            token = user.generate_reset_token()
            send_email(user.email, 'Reset Your Password',
                       'auth/email/reset_password',
                       user=user, token=token)
        flash('An email with instructions to reset your password has been '
              'sent to you.')
        return redirect(url_for('users.login'))
    return render_template('auth/reset_password1.html', form=form, title="Reset Your Password")


@users.route('/reset/<token>', methods=['GET', 'POST'])
def password_reset(token):
    if not current_user.is_anonymous:
        return redirect(url_for('core.home'))
    form = PasswordResetForm()
    if form.validate_on_submit():
        if User.reset_password(token, form.new_password.data):
            db.session.commit()
            flash('Your password has been updated.')
            return redirect(url_for('users.login'))
        else:

stead/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

stead/templates/_posts.html
<ul class="posts">
    {% for post in posts %}
    <li class="post">
        <div class="post-content">
            <div class="post-author"><{{ post.author.username }}></div>
            <div class="post-body">
                    {{ post.content }}
            </div>
            <div class="post-footer">
                <a href="{{ url_for('forum.post', id=post.id) }}#comments">
                    <span class="label label-primary">{{ post.comments.count() }} Comments</span>
                </a>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

stead/templates/all_news.html
{% extends "layout.html" %}
{% block content %}

  <div class="container" >
    <div class="row">
      <div class="col-md-12">
        <h4 style="text-align: center; text-transform: capitalize; color: black; font-size: 40px; margin-top: 20px;">Stead News</h4>
        <p class="text-center" style="font-size: 30px; font-family: Segoe UI;">Find out about the recent stories of Stead</p>
        {% if current_user.is_authenticated and current_user.is_administrator()%}
        <div class="float-right">
          <a href="{{ url_for('news_posts.create_post') }}" style="font-size: 50px; color: black;"><i class="fa fa-plus-circle"></i></a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
    

  <div class="container">
    <div class="row">
        {# Go through each blog post #}
        {% for post in blog_posts.items %}
      <div class="col-md-4 col-sm-12">
        <br>
        <div class="card" >
          <img class="card-img-top" src="{{ url_for('static', filename='news_pic/' + post.picture) }}" alt="" style="width: 100%; height: 15vw; object-fit: cover;">
          <div class="card-body">
            <a href="  {{ url_for('news_posts.blog_post', blog_post_id=post.id) }}" style="text-decoration: none"><h4 class="card-title" style="text-transform: uppercase; color: red; font-family: Arvo; font-size: 20px;">{{ post.title }}</h4></a>
            <p class="card-text">{{ post.text[:100] | safe }}...</p> <br>
            <a href="{{ url_for('news_posts.blog_post', blog_post_id=post.id) }}" style="text-decoration: none"><small class="text-muted" style="color: rgba(255, 255, 255, 0.521); font-size: 14px;">{{ post.date.strftime('%B %d, %Y') }}</small></a>
          </div>
        </div>
      </div>
      <br><br>
      {% endfor %}
    </div>


    <br>
    <div class="row">
      <div class="col-md-12">
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
              {% if blog_posts.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('news_posts.news', page=page_num) }}">{{ page_num }}</a></li>
              {% else %}
                <li class="page-item"><a class="page-link" href="{{ url_for('news_posts.news', page=page_num) }}">{{ page_num }}</a></li>
              {% endif %}
          {% endfor %}
          </ul>
        </nav>
      </div>      
    </div>      
  </div>




{% endblock %}

stead/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Acme|Akronim|Electrolize|Faster+One|Fredericka+the+Great|VT323&display=swap" rel="stylesheet">
    <!--Main body CSS -->
    <link rel="stylesheet" type="text/css" href=" {{ url_for('static', filename='css/main.css' ) }} " >
    <link rel="stylesheet" type="text/css" href=" {{ url_for('static', filename='css/style.css' ) }} " >
    <link rel="stylesheet" type="text/css" href=" {{ url_for('static', filename='css/bootstrap.css' ) }} " >
    <link rel="stylesheet" type="text/css" href=" {{ url_for('static', filename='css/bootstrap.min.css' ) }} " >

    <style>
      @import url('https://fonts.googleapis.com/css?family=Abel&display=swap');
      body{
        font-family: 'Abel', sans-serif;
      }
    </style>

    {% if title %}
        <title> Stead - {{ title }} </title>
    {% else %}
        <title>Home</title>
    {% endif %}
</head>
<body>
    <header class="nav-header">
            <nav class="navbar navbar-expand-lg navbar-light bg-light text-dark" >
                    <div class="container" >
                            <a class="navbar-brand" href=" {{url_for('core.home')}} ">STEAD</a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                              <span class="navbar-toggler-icon"></span>
                            </button>

                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                              <ul class="navbar-nav ml-auto">
                                <li class="nav-item ">
                                  <a class="nav-link" href=" {{url_for('core.home')}} ">Home <span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item">
                                  <a class="nav-link" href="{{ url_for('core.events') }}">Events</a>
                                </li>
                              {% if current_user.is_authenticated %}
                                <li class="nav-item">
                                  <a class="nav-link" href="{{ url_for('news_posts.news') }}">News</a>
                                </li>
                              {% endif %}
                                  {% if current_user.is_authenticated %}
                                       <li class="nav-item"><a class="nav-link" href="{{ url_for('core.student_list') }}">registered student</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{{ url_for('forum.forums') }}">Forum</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{{ url_for('core.account') }}">Account</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a></li>

                                    {% else %}
                                    <li class="nav-item"><a class="nav-link" href="{{ url_for('users.register') }}">Register</a></li>
                                  <li class="nav-item">
                                  <a class="nav-link" href="{{url_for('users.login')}} " >Log In </a>
                                  <!-- Modal -->
                                  <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                      <div class="modal-content">
                                        <div class="modal-header">
                                          <h5 class="modal-title" style="color: black; text-transform: uppercase;">Log In to your account</h5>
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                        </div>
                                        <div class="modal-body">
                                          <form method="GET" action="#">
                                              <input type="email" class="form-control" id="form-style"  placeholder="Enter email" required>
                                              <br>
                                              <input type="password" class="form-control" id="form-style" placeholder="Password" required>
                                              <small class="text-muted ml-2">
                                                  <a href="#">Forget Password?</a>
                                              </small>
                                              <br>
                                              <br>
                                              <button type="submit" class="btn btn-outline-success btn-md btn-block">SIGN IN</button>
                                              <div class="border-top pt-3">
                                                  <small class="text-muted">
                                                      Need an account? <a class="ml-2" href="{{ url_for('users.register') }}" >Create an account</a>
                                                  </small>
                                              </div>
                                          </form>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </li>
                                  {% endif %}
                              </ul>
                            </div>
                    </div>
            </nav>
    </header>
{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endblock %}
{% block scripts %} {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

stead/templates/post.html
{% extends "layout.html" %}


{% block title %}Flasky - Post{% endblock %}

{% block content %}


<div class="container">
    {% include '_posts.html' %}
    <h4 id="comments">Comments</h4>
    <div class="comment-form">
        <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.body.label }} 
        {{ form.body(class="form-control shadow-sm p-3 mb-2 bg-white rounded") }}
        {{ form.submit(class="btn btn-outline-info mt-2") }}<br><br>
        </form>
    </div>
    {% include '_comments.html' %}
</div>

    
{% endblock %}

stead/templates/render_field.html
{% macro render_field(field) %}
    <div class="form-group">
        <label for=" {{ field.name}} "> {{ field.label.text }} </label>
        {{ field(class_='form-control', **kwargs)|safe }}
        <ul>
            {% for error in field.errors %}
                <li style="color: red;"> {{error}} </li>
            {% endfor %}
        </ul>
    </div>
{% endmacro %}

stead/templates/user_forum.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">

    {# Go through each blog post #}
    {% for post in posts %}

    <div class="card" >

      <div class="card-body">


        <h2><a class="card-title" href="  {{ url_for('news_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.account', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
        <p>Published on: {{ post.date_posted.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.content }}</p>

      </div>
        <div class="post-footer">
          <a href="{{ url_for('forum.post', id=post.id) }}#comments">
            <span class="label label-primary">{{ post.comments.count() }} Comments</span>
          </a>
            {% if post.author == current_user %}
                <a href="{{ url_for('forum.delete_post', blog_post_id=post.id) }}">
                    <span class="label label-default">delete</span></a>
                {% endif %}
    </div>
    </div>

    {% endfor %}
</div>

{% endblock %}